# SITE SETTINGS
title: B-Cubed documentation and tutorials
author: B-Cubed partners

# SOCIAL PROFILES
social:
  twitter: BCubedProject
  github: b-cubed-eu/documentation

# THEME SETTINGS
theme: minima # Fallback theme
remote_theme: peterdesmet/petridish@3.0
tweets_on_home: false
github_edit: true
logo: /assets/images/b3-logo.png
font_serif: false
colors:
  links: "#48a529"
  banner: "#005957"
  footer: "#005957"

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: ""
      type: pages
    values:
      toc: true
