# SITE SETTINGS
title: Documentation and Tutorials
description: Documentation, tutorials and workflows for the B-Cubed toolbox.
url: https://b-cubed-eu.github.io
baseurl: /documentation
favicon = "favicon.ico"

# THEME SETTINGS
theme: just-the-docs
logo: "../images/Blogo.png"
search_enabled: true
aux_links:
  GitHub: https://github.com/b-cubed-eu/documentation
# color_scheme: B-Cubedtheme
extra_css:
  - style.css
sass:
  style: compressed
  sass_dir: _sass

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-default-layout  
  - jekyll-sass-converter
exclude:
  - README.md
