# SITE SETTINGS
title: B-Cubed documentation and tutorials
description: Documentation, tutorials and workflows for the B-Cubed toolbox.
url: https://b-cubed-eu.github.io
baseurl: ""
favicon: favicon.ico

# THEME SETTINGS
theme: just-the-docs

# Just the docs settings
logo: /assets/images/b3-logo.png
search_enabled: true
aux_links:
  GitHub: https://github.com/b-cubed-eu/documentation

# Just the docs footer (TODO: currently missing)
last_edit_timestamp: true
gh_edit_link: true
gh_edit_repository: https://github.com/b-cubed-eu/documentation

# Just the docs colours
callouts:
  important:
    color: blue
  note:
    color: yellow

# Just the docs style
# color_scheme: B-Cubedtheme
extra_css:
  - assets/css/style.css # TODO: does this work?
sass:
  style: compressed
  sass_dir: _sass

# BUILD SETTINGS
markdown: kramdown
plugins:
  - jekyll-default-layout  
  - jekyll-sass-converter
exclude:
  - README.md

# FRONTMATTER DEFAULTS
